### ISSUE TITLE
error with media query

### ISSUE THREAD

**Issue by luisrudge** [sshmyg/css2less#1]
awesome project :)
but it's failing with media queries. I guess its related with the `{` separator?

``` javascript
var css2less = require('css2less'),
  cssString = 'a {color:green;} @media (min-width: 550px) { a {color:red;} }',
  options = {},
  result;

result = css2less(cssString, options);
console.log(result);
```

```
λ node index.js

C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:193
      var value = parts[1].trim();
                           ^
TypeError: Cannot call method 'trim' of undefined
    at me.matchVendorPrefixMixin (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:193:28)
    at me.addRule (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:260:20)
    at me.addRule (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:283:10)
    at me.addRule (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:283:10)
    at me.addRule (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:283:10)
    at me.addRule (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:283:10)
    at me.generateTree (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:327:12)
    at me.processLess (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:101:8)
    at module.exports (C:\Users\deschamps\Desktop\skeleton\node_modules\css2less\index.js:475:12)
    at Object.<anonymous> (C:\Users\deschamps\Desktop\skeleton\index.js:6:10)
```

**Comment by luisrudge** [comment]
the problem is actually with the `vendorMixins` option. Setting it to false solved the issue, but the generated less is still wrong.

``` css
a {
        color:green;
}

@media {
        (min-width {
                &: {
                        550px) {
                                a;
                        }
                }
        }
}

color {
        &:red; {

        }
}
```
