### ISSUE TITLE
error with media & animate

### ISSUE THREAD

**Issue by ziyoren** [sshmyg/css2less#2]
### error with media query
```css
@media screen and (min-width: 1200px){
    .login_registerBtn{
        width:30%;
    }
}
```

```shell
# parts = [ '.login_registerBtn' ]
***/node_modules/css2less/index.js:191
			var value = parts[1].trim();
			                    ^

TypeError: Cannot read property 'trim' of undefined
```

### animate
```css

@-webkit-keyframes animate {
  0% { -webkit-transform: perspective(160px); }
  50% { -webkit-transform: perspective(160px) rotateY(-180deg); }
  100% { -webkit-transform: perspective(160px) rotateY(-180deg) rotateX(-180deg); }
}

@keyframes animate {
  0% {
    transform: perspective(160px) rotateX(0deg) rotateY(0deg);
    -webkit-transform: perspective(160px) rotateX(0deg) rotateY(0deg);
  } 50% {
    transform: perspective(160px) rotateX(-180deg) rotateY(0deg);
    -webkit-transform: perspective(160px) rotateX(-180deg) rotateY(0deg) ;
  } 100% {
    transform: perspective(160px) rotateX(-180deg) rotateY(-180deg);
    -webkit-transform: perspective(160px) rotateX(-180deg) rotateY(-180deg);
  }
}

```

```shell
# parts = [ '0%' ]
***/node_modules/css2less/index.js:191
			var value = parts[1].trim();
			                    ^

TypeError: Cannot read property 'trim' of undefined
```
